### ISSUE TITLE
Fix of #13 introduces StackOverflowError

### ISSUE THREAD

**Issue by Kdecherf** [CleverCloud/Quercus#16]
Commit b2763fb068e041074f6b82e782b6464e6388c360 (fix for #13) introduces a stackoverflowerror in some part of Quercus ...

Branch 'master' now fails.

**Comment by terefang** [comment]
seams you need to copy ConstStringValue to ConstUnicodeStringValue and let it extend from UnicodeBuilder to have isStatic == true

**Comment by Kdecherf** [comment]
In reality the SOF isn't linked to this commit (deployment fail), closing issue.
