### ISSUE TITLE
Il manque une constante à PDO, MYSQL_ATTR_INIT_COMMAND

### ISSUE THREAD

**Issue by ahoy-jon** [CleverCloud/Quercus#29]
L'erreur c'est  : PDO::MYSQL_ATTR_INIT_COMMAND is an unknown constant

genre pour : 

$connection = new PDO("mysql:host=".$CONFIG['Database']['host'].";dbname=".$CONFIG['Database']['db'], $CONFIG['Database']['login'], $CONFIG['Database']['password'], array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET CHARACTER SET utf8",PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION));

Après, cette constante est déjà spécifique à certains drivers mysql pour PHP, donc je doute que cela soit une bonne idée de la gérer.

**Comment by Kdecherf** [comment]
Ok vu, ceci étant dit j'ai l'impression qu'il faut également gérer sa prise en charge du côté de la classe même.

Je vais vérifier le code source de PDO.

**Comment by ahoy-jon** [comment]
Ok !

// mince, j'ai fermé le bug.
