### ISSUE TITLE
Version en unspecified

### ISSUE THREAD

**Issue by ahoy-jon** [CleverCloud/Quercus#30]
Quand je rejoute l'upload d'archive dans le build.gradle pour publier dans des repos maven : 

  <pre>
 subprojects {
     repositories {
         mavenRepo urls: "http://download.java.net/maven/2/"
     }
+
-    apply plugin: 'maven'
  +
-         uploadArchives {
-             repositories.mavenDeployer {
-                 repository(url: "file:////Users/jon/.m2/repository")
-             }
-         }
  }
  </pre>

Cela fait des versions unspecified. Est-ce qu'il ne vaudrait pas mieux que tu décides d'une version ?

**Comment by Kdecherf** [comment]
Je vais vérifier, sachant que la version est calculée via le fichier bin/prepareJava.sh
